[package]
name = "muxbar"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
chrono = "0.4.38"
sysinfo = "0.30.7"
# time = { version = "0.3.37", features = [
#   "serde",
#   "macros",
#   "formatting",
#   "local-offset",
# ] }
